### ISSUE TITLE
apm vs apm-beta

### ISSUE THREAD

**Issue by Arcanemagus** [semantic-release/apm-config#7]
When Atom is installed on a *NIX platform the beta channel releases don't actually provide `apm`, instead that utility is provided as `apm-beta`. If the CI build is setup so the beta build runs "last" and `semantic-release` runs there, it can't find `apm` and fails.

I see two solutions to this:
* Allow `apm-config` to use `apm-beta`
    * I don't think this is the _right_ solution, because by its very nature the Beta channel builds are not supposed to be trusted.
* Explicitly note in the documentation that `semantic-release` should only be ran on builds for the stable channel of Atom.

If you agree that the second option is the way to go I can put up a quick PR updating the documentation 😉.

See https://github.com/AtomLinter/atom-linter-pug/pull/22 for an example where this issue was fixed.

**Comment by pvdlg** [comment]
Just to be sure, what's the difference between `apm publish` and `apm-beta publish` is it just the `apm` CLI that is in a more recent/beta version or does that change the way the package is published (like make it available only for Atom beta users)?

If the publish is actually different we might want to support both (and still clarify in the doc) in case users want to release on the beta channel.

If the publish is the same then the second solution (doc) is the best. In addition we can add another verification that makes sure the environment variable `ATOM_CHANNEL` is set to `stable` (or empty if `stable` is the default).
This way we can display an error message to users who didn't read the doc.

**Comment by Arcanemagus** [comment]
`apm` and `apm-beta` are _theoretically_ identical, the only difference is that `apm-beta` goes with a version of Atom from the beta channel (for easy distinction between the two when both Stable and Beta are installed on the same system).

So assuming that the Beta channel hasn't introduced any bugs in `apm` it should be fine to use either of them, I suggested a documentation update just because it's safer to only rely on the Stable channel version.

> In addition we can add another verification that makes sure the environment variable ATOM_CHANNEL is set to stable (or empty if stable is the default).

Although probably everyone is using the build scripts from `atom/ci`, it's not actually a requirement so that environment variable, although useful if present, probably isn't the best to use as a required thing.

**Comment by pvdlg** [comment]
Ok, thanks for the clarifications. Let's go for the doc update then.
