### ISSUE TITLE
@semantic-release/apm-config@latest fails with v16

### ISSUE THREAD

**Issue by UziTech** [semantic-release/apm-config#90]
The `@latest` version of `@semantic-release/apm-config` on npm is v6.0.2 which does not work with the `@latest` version of `semantic-release` v16.

Could you move `@semantic-release/apm-config` v7.0.0 to the `@latest` tag on npm?

The error I get is: https://github.com/semantic-release/semantic-release/issues/1293

**Comment by pvdlg** [comment]
Done. Good catch! Thanks
